front/web/views/base.py
from flask import Blueprint, render_template

bp = Blueprint('base',__name__,url_prefix='/')



'''
    테스트용 파일 삭제할 예정
'''


@bp.route('/base')
def base():
    return render_template('base.html')

@bp.route('/test')
def test():
    return render_template('test.html')

front/web/views/manager.py
from flask import Blueprint, render_template, request, session, redirect, url_for, flash, abort
from werkzeug.utils import secure_filename
from ..models import Problem, Flag
from .. import db
from flask import jsonify
import os
UPLOAD_FOLDER = os.getcwd() + '/upload'  # 절대 파일 경로
ALLOWED_EXTENSIONS = set(['txt', 'pdf', 'png', 'jpg', 'jpeg', 'gif','py'])

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


man_bp = Blueprint('manager',__name__,url_prefix='/')


# @user_bp.route('/login/')
@man_bp.route('/manager', methods=['POST','GET'])
def manager():
        if 'logged_in' in session and session['logged_in']:
        
                if request.method == 'POST':
                        category = request.form.get('category')
                        title = request.form.get('title')
                        content = request.form.get('content')
                        hint = request.form.get('hint')
                        conn = request.form.get('connect')
                        score = int(request.form.get('score'))
                        file = request.files.get('file')
                        flag = request.form.get('flag')
                        ptype = request.form.get('ptype')
                        if title and content:  # title과 content가 모두 존재하는지 확인
                                # 여기다가 db에 넣는거 작성
                                if file and allowed_file(file.filename):
                                        filename = secure_filename(file.filename)
                                        file_path = os.path.join(UPLOAD_FOLDER, filename)
                                        file.save(file_path)
                                        p = Problem(category,title,content,hint,conn,score,file_path,ptype)
                                        
                                else:
                                        p = Problem(category,title,content,hint,conn,score,"파일없음",ptype)
                                
                                db.session.add(p)
                                db.session.commit()
                                
                                f = Flag(p.p_idx,flag,score)
                                db.session.add(f)
                                db.session.commit()
                                flash("문제 생성 완료")
                                return redirect(request.referrer or '/')

                return render_template('manager.html')
        else :
                abort(404)

@man_bp.route('/manager/list')
def list():
      if 'logged_in' in session and session['logged_in']: 
        p = Problem.query.all()
        return render_template('m_list.html', problems=p)
      else:
            abort(404)


@man_bp.route('/edit_problem/<int:p_idx>', methods=['GET', 'POST'])
def edit_problem(p_idx):

        if 'logged_in' in session and session['logged_in']:
                problem = Problem.query.filter_by(p_idx = p_idx).first()
                flag = Flag.query.filter_by(p_idx = p_idx).first()
                if problem is None:
                        abort(404)

                if request.method == 'POST':
                
                        problem.category = request.form['category']
                        problem.title = request.form['title']
                        problem.contents = request.form['content']
                        problem.hint = request.form['hint']
                        problem.connect = request.form['connect']
                        problem.score = int(request.form['score'])
                        flag.flag = request.form['flag']
                        
                        # 파일 업로드 처리
                        file = request.files.get('file')
                        if file:
                                filepath = os.path.join(UPLOAD_FOLDER, file.filename)
                                file.save(filepath)
                                problem.filepath = filepath
                        try:
                                db.session.commit()
                                return redirect(url_for('manager.list'))
                        except Exception as e:
                                db.session.rollback()
                                return jsonify({"error": str(e)}), 500
        
                # 문제 데이터를 수정 페이지에 전달
                return render_template('edit_problem.html', problem=problem, flag=flag)
        
        else:
               abort(404)

front/web/views/problem.py
from flask import Blueprint, render_template, abort,send_file,redirect,session,request,jsonify , url_for
from ..models import Problem, User ,Conn
from sqlalchemy import desc
import os
import requests
from .. import db
import json
problem_bp = Blueprint('problem',__name__,url_prefix='/')

            

@problem_bp.route('/<category>/problem<int:id>', methods=['GET','POST'] )
def p(category,id):
    
    if request.method == "POST":
        
        user = session.get('username')
        if user is not None:    
            u  = User.query.filter(User.id == user).first()
            
            if u is not None:    # 
                conn = Conn.query.filter(Conn.u_idx == u.u_idx).first()
                if conn is not None : 
                    ''' 유저가 이미 연결 정보를 가지고 있을때의 처리'''
                    return jsonify({"message": "Already connected", "port": conn.port})
                else:    
                    
                    p = Problem.query.filter_by(category=category).order_by(desc(Problem.p_idx)).all()
                    if id >0  and id <= len(p):
                        pro = p[id-1]
                        server_url = "http://example.com/create/" + category +"/"+ pro.connect
                        print(server_url)
                        
                        try:                        
                        # 서버에 POST 요청
                            response = requests.post(server_url)
                            
                        # 요청이 성공했을 경우
                            
                            if response.status_code == 201:
                                server_info = response.json()
                               
                                port = int(server_info.get("port"))
                                port_info = {"conn": "This is your AWS EC2 IP:" , "port": port , "title":pro.title}
                                container_name = server_info.get("container_name")
                                newconn = Conn(u.u_idx , pro.p_idx, port, container_name)
                               
                                db.session.add(newconn)
                                try:
                                    db.session.commit()
                                except Exception as e:
                                    db.session.rollback()
                                
                                return jsonify(port_info)
                            else:
                            # 요청이 실패한 경우, 오류를 반환합니다.
                                return jsonify({"error": "Failed to get server info"}), response.status_code
                        except Exception as e:
                        # 예외가 발생한 경우, 오류를 반환합니다.
                            print(e)
                            return jsonify({"error": str(e)}), 500
                    else:
                        abort(404)
            else: 
                return jsonify({"error": "No user information"})
        else:
            return jsonify({"error": "No user"})
    
    
    else :
        problem = Problem.query.filter_by(category=category).order_by(desc(Problem.p_idx)).all()
        user =  session.get('username')
        if user is not None:
            user = User.query.filter_by(id = user).first()
        if id >0  and id <= len(problem):
            pro = problem[id-1]
            check = False

            if user and user.has_solved(pro.p_idx):
                check = True
            
            return render_template('problem.html', pro = pro, number = id, check = check, user = user)
        else:
            abort(404)
            
   
@problem_bp.route('/download/problem/<int:problem_number>' , methods=['POST'])
def download_problem(problem_number):
    id = problem_number
    problem = Problem.query.order_by(desc(Problem.p_idx)).all()
    
    if id >0  and id <= len(problem):
        pro = problem[id-1]
    return send_file(pro.filepath , as_attachment=True)
   




@problem_bp.route('/server-status', methods=['GET'])
def server_status():
    user = session.get('username')
    if user is not None:
        u = User.query.filter(User.id == user).first()
        if u is not None:
            conn = Conn.query.filter(Conn.u_idx == u.u_idx).first()
            if conn is not None:
                p = Problem.query.filter(Problem.p_idx == conn.p_idx).first()
                return jsonify({"status": "connected", "port": conn.port, "title": p.title , "conn": "This is your AWS EC2 IP:"})
            else:
                return jsonify({"status": "disconnected"})
        else:
            return jsonify({"error": "No user information"}), 404
    else:
        return jsonify({"error": "No user"}), 404
    
    
    
@problem_bp.route('/<category>/problem<int:id>/close-server', methods=['POST'])
def close_server(category, id):
    data = request.get_json()
    port = data.get('port')
    user = session.get('username')
    if user is not None:    
        u  = User.query.filter(User.id == user).first()
        if u is not None:  
            p = Problem.query.filter_by(category=category).order_by(desc(Problem.p_idx)).all()
            if id >0  and id <= len(p):
                pro = p[id-1]
                conn = Conn.query.filter(Conn.u_idx == u.u_idx).first()
                server_url = "http://example.com/down/" + conn.container_name
                try:                        
                # 서버에 POST 요청
                    response = requests.post(server_url)
                # 요청이 성공했을 경우
                    if response.status_code == 200:
                        db.session.delete(conn)
                        try:
                            db.session.commit()
                        except Exception as e:
                            db.session.rollback()
                        
                        return jsonify({"success": "삭제성공"}), 200
                    else:
                    # 요청이 실패한 경우, 오류를 반환합니다.
                        return jsonify({"error": "Failed to get server info"}), response.status_code
                except Exception as e:
                # 예외가 발생한 경우, 오류를 반환합니다.
                    return jsonify({"error": str(e)}), 500
            else:
                abort(404)    
        else: 
            return jsonify({"error": "No user information"})
    else:
        return jsonify({"error": "No user"})
    


    
@problem_bp.route('/disconnect/', methods=['POST'])
def disconn():
    try:
        data = json.loads(request.data)
        container_name = data.get('container_name')
        print(container_name)
        c = Conn.query.filter_by(container_name=container_name).first()
        print(c)
        if c:
            db.session.delete(c)
            try:
                db.session.commit()
            except Exception as e:
                db.session.rollback()
        return jsonify({"success": "삭제성공"}), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 400

front/web/views/user.py
from flask import Blueprint, render_template, request, session, redirect, url_for,flash ,current_app 
from ..models import User
from .. import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_bcrypt import Bcrypt
from .. import bcrypt
user_bp = Blueprint('user',__name__,url_prefix='/')



# @user_bp.route('/login/')
@user_bp.route('/login', methods=['POST'])
@user_bp.route('/login/', methods=['POST'])
def login():
        id = request.form['id']
        pw = request.form['pw']

        user = User.query.filter_by(id=id).first()
        if user and bcrypt.check_password_hash(user.pw,pw):
            session['username'] = user.id
            
            if(user.getAuth() == 2):
                session['logged_in'] = True
            else:
                session['logged_in'] = False
            flash('로그인 성공')
            return  redirect(request.referrer or '/')
        else:
            flash('로그인 실패')
            return  redirect(request.referrer or '/')
    
@user_bp.route('/logout')
@user_bp.route('/logout/')
def logout():
    if session.pop('username', None) is None:
        flash("로그인을 먼저 진행해 주세요")
        return  redirect(request.referrer or '/')
    else:
        session.pop('logged_in', None)
        flash("로그아웃 성공")
        return  redirect(request.referrer or '/')

# 회원가입 페이지 라우트
@user_bp.route('/signup', methods=['POST'])
def signup():
    id = request.form['id']
    pw = request.form['pw']
    confirm_pw = request.form['confirm']
    email = request.form['email']
    nick = request.form['nick']

    # 백엔드 유효성 검사
    if not re.match(r"^[a-zA-Z0-9_]+$", id):
        flash("아이디는 알파벳, 숫자, 밑줄만 포함할 수 있습니다.")
        return redirect(request.referrer or '/')

    if len(id) < 4 or len(id) > 12:
        flash("아이디는 4자 이상, 12자 이하여야 합니다.")
        return redirect(request.referrer or '/')

    if len(pw) < 8:
        flash("비밀번호는 최소 8자 이상이어야 합니다.")
        return redirect(request.referrer or '/')

    if not re.match(r"[^@]+@[^@]+\.[^@]+", email):
        flash("유효한 이메일 주소를 입력해주세요.")
        return redirect(request.referrer or '/')

    if len(nick) < 2 or len(nick) > 20:
        flash("닉네임은 2자 이상, 20자 이하여야 합니다.")
        return redirect(request.referrer or '/')

    if pw != confirm_pw:
        flash("비밀번호가 일치하지 않습니다.")
        return redirect(request.referrer or '/')

    if not re.match(r'^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$', pw):
        flash("비밀번호는 8자 이상이며, 영문자, 숫자, 특수문자(@$!%*#?&)를 최소 1개씩 포함해야 합니다.")
        return redirect(request.referrer or '/')

    existing_user = User.query.filter_by(id=id).first()
    if existing_user:
        flash("이미 존재하는 아이디입니다.")
        return redirect(request.referrer or '/')
    else:
        new_user = User(id, bcrypt.generate_password_hash(pw).decode('utf-8'), nick, email)
        db.session.add(new_user)
        try:
            db.session.commit()
            flash("회원가입하였습니다.")
            return redirect(request.referrer or '/')
        except Exception as e:
            db.session.rollback()
            flash("오류가 발생했습니다.")
            return redirect(request.referrer or '/')
        
        
@user_bp.route('/prfl', methods=['GET'])
def profile():
        username = session.get('username')
        if username is not None:
            user = User.query.filter(User.id == username).first()
            return render_template('mypage/profile.html', data = user)

front/web/templates/_footer.html
<div class="footer">
<div class="container">

    
    <div class="row-footer">
        <div class="col-footer">
            © 2024 Capstone
        </div>
        <div class="col-footer">
            Legal & Compliance
        </div>
        <div class="col-footer">
            Website T&Cs
        </div>
        <div class="col-footer">
            Privacy Notice
        </div>
    </div>
</div>


</div>

front/web/templates/_nav.html
<header class="header">
    <div class="header-item">
    <a href="/">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
            stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <polyline points="4 17 10 11 4 5"></polyline>
            <line x1="12" x2="20" y1="19" y2="19"></line>
        </svg>
        Cyber Range
    </a>
    </div>
    <div class="header-nav">
        <ul>
            <li>
                <a href="/board">Practice</a>
            </li>
            <li>
                <a style="text-decoration:line-through; ">Scenario</a>
            </li>
            <li>
                <a href="/score">Score Board</a>
            </li>
            <li>
                <a href="/board/QNA">Q & A</a>
            </li>
        </ul>
    </div>
    <nav class="header-item">
        {% if 'username' in session %}
        <a href="{{url_for('user.profile')}}">
            <span>{{session['username']}} 님 환영합니다</span>
        </a>
        <a href="{{url_for('user.logout')}}">
            <span>로그아웃</span>
        </a>
        {% else %}
        <a id="loginBtn">
            <span>로그인</span>
        </a>
        {% endif %}
    </nav>
    
</header>

front/web/templates/base.html
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Cyber Range{% endblock %}</title>
    <!-- import tailwind css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
    
    <style>
        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            font-family: 'Comfortaa', sans-serif;
            --font-sans: 'Comfortaa';
        }

        body {
            font-family: 'Gabarito', sans-serif;
            --font-sans: 'Gabarito';
        }
    </style>
</head>

<body class="base-body">
   
    <div class="base-div">
        {% include("_nav.html") %}

        <div class="modal" id="modal" style="display: none;">
            <div class="modal-content">

                <button class="close-modal" id="close-modal">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"
                        style="width: 20px; height: 20px;">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>

                <div class="form signin">
                    <div class="form-header">
                        <div class="show-signin">Sign In</div>
                        <div class="show-signup">Sign Up</div>
                    </div>
                    <div class="arrow"></div>
                    <div id="validation-message" style="color: red;"></div>
                    <form id="form" action="/login" method="POST">
                        <div class="form-elements">
                            <div class="form-element">
                                <input type="text" id="username"name="id" placeholder="Username">
                            </div>
                            <div class="form-element">
                                <input type="password" id="password" name="pw" placeholder="Password">
                            </div>
                            <div class="form-element" style="display:none">
                                <input type="password" id="confirm" name="cpw" placeholder="Confirm password">
                            </div>
                            <div class="form-element" style="display:none">
                                <input type="eamil" id="email" name="email" placeholder="Email">
                            </div>
                            <div class="form-element" style="display:none">
                                <input type="text" id="nick" name="nick" placeholder="nickName">
                            </div>
                            <div class="form-element">
                                <button type="submit" id="submit-btn">Sign In</button>
                            </div>
                        </div>
                    </form>
                   
                </div>
            </div>
        </div>

        <main class="content">
            {% block content %}
            {% endblock %}
        </main>
        {% include("_footer.html") %}
    </div>
    
    {%with messages = get_flashed_messages()%}
    {%if messages %}
      <script type="text/javascript">
        alert("{{messages[-1]}}");
      </script>
      {%endif%}
    {%endwith%}
</body>


<script src="{{ url_for('static',filename='js/login.js')}}"></script>
</html>

front/web/templates/board.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} - {{title}}
{% endblock %}



{% block content %}
<div class="container">
    <div class="practice">
        <h2> Practice </h2>
    </div>

    <div class="row">
        <div class="col">
            <div class="vul-data" onclick="location.href='/board/web';">

                <div class="itemcontent">

                    <div>
                        <h3>Web</h3><br>
                        <p>웹 취약점과 관련된 문제를 풀 수 있습니다.</p>
                    </div>


                </div>
                <div class="itemimage">
                    <img class="img-fluid" src="{{url_for('static', filename='images/web.jpg')}}" alt="placeholder">
                </div>

            </div>
        </div>
        <div class="col">
            <div class="vul-data" onclick="location.href='/board/system';">
                <div class="itemcontent">
                    <div>
                        <h3>System</h3><br>
                        <p>시스템 취약점과 관련된 문제를 풀 수 있습니다.</p>
                    </div>

                </div>
                <div class="itemimage">
                    <img class="img-fluid" src="{{url_for('static', filename='images/system.jpg')}}" alt="placeholder">
                </div>
            </div>
        </div>
        <div class="col">
            <div class="vul-data" onclick="location.href='/board/malware';">
                <div class="itemcontent">
                    <div>
                        <h3>Malware</h3><br>
                        <p>악성코드와 관련된 문제를 풀 수 있습니다.</p>
                    </div>

                </div>
                <div class="itemimage">
                    <img class="img-fluid" src="{{url_for('static', filename='images/malware.png')}}" alt="placeholder">
                </div>
            </div>
        </div>
        <div class="col">
            <div class="vul-data" onclick="location.href='/board/misc';">
                <div class="itemcontent">
                    <div>
                        <h3>misc</h3><br>
                        <p>misc와 관련된 문제를 풀 수 있습니다.</p>
                    </div>

                </div>
                <div class="itemimage">
                    <img class="img-fluid" src="{{url_for('static', filename='images/cloud.jpg')}}" alt="placeholder">
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

front/web/templates/edit_problem.html
<!-- edit_problem.html -->
{% extends 'base.html' %}

{% block title %}
문제 수정 페이지
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/manager.css') }}">
<link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor.min.css" />
<div>
    <h2 style="color:wheat">문제 수정</h2>
</div>
<div></div>
<div>
    <form id="mainform" action="{{ url_for('manager.edit_problem', p_idx=problem.p_idx) }}" method="POST"
        enctype="multipart/form-data">
        <div class="form-elements">
            <div class="form-element">
                <select name="ptype">
                    <option value="practice" {% if problem.problem_type=='practice' %}selected{% endif %}>practice
                    </option>
                    <option value="scenario" {% if problem.problem_type=='scenario' %}selected{% endif %}>scenario
                    </option>
                </select>
            </div>

            <div class="form-element">
                <select name="category">
                    <option value="system" {% if problem.category=='system' %}selected{% endif %}>system</option>
                    <option value="web" {% if problem.category=='web' %}selected{% endif %}>web</option>
                    <option value="malware" {% if problem.category=='malware' %}selected{% endif %}>malware</option>
                    <option value="misc" {% if problem.category=='misc' %}selected{% endif %}>misc</option>
                </select>
            </div>
            <div class="form-element">
                <input type="text" name="title" placeholder="제목" value="{{ problem.title }}" autocomplete="off">
            </div>
            <div class="form-element">
                <label for="content">내용</label>
                <textarea id="content" name="content" autocomplete="off"
                    style="display:none;">{{ problem.contents }}</textarea>
            </div>
            <div id="editor"></div>
            <div class="form-element">
                <input type="text" name="hint" placeholder="힌트" value="{{ problem.hint }}" autocomplete="off">
            </div>
            <div class="form-element">
                <input type="text" name="connect" placeholder="연결정보" value="{{ problem.connect }}" autocomplete="off">
            </div>
            <div class="form-element">
                <input type="text" name="score" placeholder="점수" value="{{ problem.score }}" autocomplete="off">
            </div>
            <div class="form-element">
                <input type="file" name="file" placeholder="파일" autocomplete="off">
                {% if problem.filepath %}
                <p>현재 파일: {{ problem.filepath }}</p>
                {% endif %}
            </div>
            <div class="form-element">
                <input type="text" name="flag" placeholder="정답" value="{{ flag.flag }}" class="flag" autocomplete="off">
            </div>
            <div class="form-element">
                <button type="submit" id="submit-btn2">수정</button>
            </div>
        </div>
    </form>
</div>

<div>
    <h2><a href="/manager/list">문제 리스트</a></h2>
</div>
<script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
<script>
    const editor = new toastui.Editor({
        el: document.querySelector('#editor'), // 에디터를 적용할 요소 (컨테이너)
        height: 'auto',                        // 에디터 영역의 높이 값 (OOOpx || auto)
        initialEditType: 'wysiwyg',            // 최초로 보여줄 에디터 타입 (markdown || wysiwyg)
        initialValue: document.querySelector('#content').value, // 내용의 초기 값으로, 반드시 마크다운 문자열 형태여야 함
        previewStyle: 'vertical',                // 마크다운 프리뷰 스타일 (tab || vertical)
        hooks: {
            addImageBlobHook: async (blob, callback) => {
                const formData = new FormData();
                formData.append('file', blob);

                const response = await fetch('/upload_image', {
                    method: 'POST',
                    body: formData
                });

                const result = await response.json();
                if (result.url) {
                    callback(result.url, 'alt text');
                } else {
                    alert('이미지 업로드에 실패했습니다.');
                }
            }
        }
    });

    // Update the textarea content with the editor content before form submission
    document.querySelector('#mainform').addEventListener('submit', function (event) {
        document.querySelector('#content').value = editor.getMarkdown();
    });
</script>
{% endblock %}

front/web/templates/m_list.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} - {{title}}_{{id}}
{% endblock %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/manager.css') }}">
<table class="">
    <thead>
        <tr>
            <th>문제 번호</th>
            <th>카테고리</th>
            <th>제목</th>
            <th>내용</th>
            <th>힌트</th>
            <th>접속정보</th>
            <th>점수</th>
        </tr>
    </thead>
    <tbody>
        {% for p in problems %}
        <tr data-href="{{ url_for('manager.edit_problem', p_idx=p.p_idx) }}" style="cursor: pointer;">
            <td>{{ p.p_idx }}</td>
            <td>{{ p.category }}</td>
            <td>{{ p.title }}</td>
            <td>{{ p.contents }}</td>
            <td>{{ p.hint }}</td>
            <td>{{ p.connect }}</td>
            <td>{{ p.score }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var rows = document.querySelectorAll('tr[data-href]');
        rows.forEach(function (row) {
            row.addEventListener('click', function () {
                window.location.href = row.getAttribute('data-href');
            });
        });
    });
</script>

{% endblock %}

front/web/templates/problem.html
{% extends 'base.html' %}

{% block title %}
{{ super() }} - 문제 설명
{% endblock %}

{% block content %}

<style>
    .loading {
        background-color: gray !important;
        cursor: not-allowed !important;
    }
</style>
<link rel="stylesheet" href="https://uicdn.toast.com/editor/latest/toastui-editor-viewer.min.css" />
<div class="problem-container">
    <div class="problem-header">
        <div class="problem-type">
            <h1>{{pro.category}}</h1>
            <h2>{{pro.score}}P</h2>
        </div>
        <div class="problem-title">
            <h1>{{pro.title}}</h1>
        </div>
    </div>

    <div class="problem-contents">
        <h1>설명</h1>
        <div id="viewer-content"></div>
        <p id="hint">{{pro.hint}}</p>
        <button id="show-hint-btn" type="button">힌트 보기</button>
    </div>
    {% if user is not none and pro.category != 'misc' %}
    <button id="server-action-btn">서버 연결 요청 하기</button>
    <script src="{{url_for('static',filename='js/s.js')}}"></script>
    <div id="result"></div>
    {% endif %}
    {% if pro.filepath != "파일없음" %}
    <div class="problem-file">
        <h1> 파일 다운로드</h1>
        <form id="downloadForm" action="{{ url_for('problem.download_problem', problem_number = number) }}"
            method="POST">
            <button type="submit" formmethod="POST">Download Problem</button>
        </form>
    </div>
    {% endif %}

    {% if not check and 'username' in session %}<!-- Input flag form -->
    <form action="/flag" method="post" class="flag-form">
        <div class="form-group">
            <label for="flag">플래그</label>
            <input type="text" id="flag" name="flag" placeholder="flag 값을 입력해주세요" required>

        </div>
        <input type="hidden" name="title" value="{{pro.title}}">
        <button type="submit">제출</button>
    </form>
    {% endif %}
</div>
<script src="{{url_for('static',filename='js/button.js')}}"></script>

<script src="https://uicdn.toast.com/editor/latest/toastui-editor-viewer.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const viewer = new toastui.Editor({
            el: document.querySelector('#viewer-content'),
            viewer: true,
            initialValue: `{{ pro.contents | replace('\n', '\\n') | safe }}`
        });
    });
</script>
{% endblock %}

front/web/templates/score.html
{% extends 'base.html' %}

{% block title %}
ScoreBoard
{% endblock %}

{% block content %}
<div class="table-wrapper">
<table class="score">
    <thead>
        <tr>
            <th>rank</th>
            <th> name </th>
            <th>score</th>
        </tr>
    </thead>
    <tbody>
        {% for item in list %}
        <tr>
            <td>{{ loop.index }}</td>
            <td>{{ item.nickname }}</td>
            <td>{{ item.t_score }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock %}